### PR TITLE
r5x: tweak for more perf

### PR DESCRIPTION
**Pull request by gut2der**

### CODE REVIEW

**Comment by Amritorock** [comment]
Hello retard

**Comment by agam778** [comment]
@gut2der can you please teach me that how to become a pro like you? 🙂🙂

**Comment by gut2der** [comment]
> @gut2der can you please teach me that how to become a pro like you? 🙂🙂

ofcourse sur, just rm -rf / and you're good to go

**Comment by JaswantTeja** [comment]
> @gut2der can you please teach me that how to become a pro like you? 🙂🙂

Just Apply This Commits In Your Device Tree,You Will Become Pro Ultra Pro Max Like Him

**Comment by eun0115** [comment]
lmfao

**Pull request closed without merging**
